# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# react-native-fcm should support FB 4, but latest breaks builds, hence older version
# pod 'Firebase/Messaging'
pod 'Firebase/Messaging', '3.17.0'

target 'StatusIm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StatusIm
  pod 'Instabug', '~> 7.0'

  target 'StatusImTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
